name: Imagine.
favicon: null
layout_spectrum: 0.2287563926074654
typography_spectrum: 0.3848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0808'
    - '#494440'
    - '#8d8c87'
    - '#d9d8d3'
    - '#fefef9'
  brandStrength: 0.9812282284256071
  lightness: 0.04405479948036373
  saturation: 0.23806051979772747
  rhythmicContrast: 0.943220216082409
purpose: []
